#!/bin/sh
# dist: public

EXE=$1
PID=$2
TYPE=$3
TMP=gdbcmds.$$.tmp
DATE=$(date +%Y%m%d-%H%M%S)

mkdir -p bt
exec >bt/$DATE-$TYPE-$PID.bt 2>&1

echo >$TMP '
set height 0
set print symbol-filename on
set print symbol on
set print array on
set print array-indexes on
set print frame-arguments all
set print pretty on
set print union on
set print object on
info thread
thread apply all bt full
quit
'

gdb -batch -x $TMP $EXE $PID </dev/null
rm -f $TMP
