#!/bin/sh

nodes='4b 6f 3a 7b 8h 6b 1e 5a 9b 5b 9e 7f 7h 1c 2c'

if [ "$1" = "-k" ]; then
	cmd="./end"
else
	cmd="./start ${1:-3}"
fi

for n in $nodes; do
	echo "running $cmd on $n"
	ssh -f $n "cd $HOME/private/loadgen; $cmd >/dev/null 2>/dev/null"
done
